default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: rails_migration_comments_development

development_mysql:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: rails_migration_comments_development
  pool: 5
  username: root
  password:
  host: localhost
  port: 3306

test:
  <<: *default
  database: rails_migration_comments_test

production:
  <<: *default
  database: rails_migration_comments_production
  username: rails_migration_comments
  password: <%= ENV['RAILS_MIGRATION_COMMENTS_DATABASE_PASSWORD'] %>
