# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65ceeca2c0476a45574d4546613f168a58af2653497568f345da5f7d363d66d90c990f419b3287375c7658f10fbf7ec0187d7a70078e319c5680b076e08030f8

test:
  secret_key_base: b1f787b8bf5d65bf486288400c6fea1957975a1c0a099613e7af4eed1313ad8b4d5a4221dc1bf3b6f4d4356c5140a8dc33b4b04a1c622f15c0fb6d24adb3a84c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
