# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 852162d371c7ba2295eb58ec0435d79318456f84c5620e5af3150acdf01d11b62ed45d9d4897bb0e170f7362c4998eabba7e88180ce41021914d8a27d3c257d0

test:
  secret_key_base: a673847081487b0a4187b38650f3f2386f17efd4f14094d513314577f89d5321003edc1a56f676bf98b73a690d1075fc3980e580448c69d3d6c3c7f513799310

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
