# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1df2978f0036819b81bf9813bbeb95c3732892d673d8fe2f1db59d1802f44d07e3157a60b02965a524706b162524bc71cc062d31d352b876858064258b8ec551

test:
  secret_key_base: c36ed547d85582b273901979e915b5357793441b50a9c9fa513f2c55b86e7f82057205bdfac01e07218b971718ca822442c44e2c363882e4fcb3ee1423a5ade9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
